#!/bin/bash

# AI Persona OS — Daily Ops
# Automated daily operations check
# By Jeff J Hunter — https://jeffjhunter.com

WORKSPACE="${1:-$HOME/workspace}"
TODAY=$(date +%Y-%m-%d)

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  AI Persona OS — Daily Ops"
echo "  $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Step 1: Check if today's log exists
echo "📅 Checking today's log..."
if [ ! -f "$WORKSPACE/memory/$TODAY.md" ]; then
    echo "   Creating $TODAY.md..."
    cat > "$WORKSPACE/memory/$TODAY.md" << EOF
# $TODAY — $(date +%A)

## Heartbeat

**Completed:** $(date +%H:%M)
**Status:** 🟢
**Focus:** [Set your focus]

## Session Notes

[What happened today]

## Decisions Made

| Decision | Reasoning | Time |
|----------|-----------|------|

## Action Items

### In Progress
- [ ] 

## Learnings

- 

## Checkpoints

---

*Generated by AI Persona OS daily-ops*
EOF
    echo "   ✓ Created"
else
    echo "   ✓ Already exists"
fi

# Step 2: Check for pending items from yesterday
echo ""
echo "📋 Checking yesterday's pending items..."
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d 2>/dev/null)
if [ -f "$WORKSPACE/memory/$YESTERDAY.md" ]; then
    pending=$(grep -c "^\- \[ \]" "$WORKSPACE/memory/$YESTERDAY.md" 2>/dev/null || echo "0")
    if [ "$pending" -gt 0 ]; then
        echo "   ⚠️  $pending uncompleted items from yesterday"
    else
        echo "   ✓ No pending items"
    fi
else
    echo "   ○ No log from yesterday"
fi

# Step 3: Check MEMORY.md size
echo ""
echo "💾 Checking MEMORY.md size..."
if [ -f "$WORKSPACE/MEMORY.md" ]; then
    size=$(wc -c < "$WORKSPACE/MEMORY.md")
    if [ "$size" -gt 4096 ]; then
        echo "   ⚠️  $size bytes (should be < 4096)"
    else
        echo "   ✓ $size bytes (OK)"
    fi
fi

# Step 4: Check .learnings for items to review
echo ""
echo "📈 Checking learning system..."
if [ -d "$WORKSPACE/.learnings" ]; then
    pending=$(grep -c "pending" "$WORKSPACE/.learnings/LEARNINGS.md" 2>/dev/null || echo "0")
    if [ "$pending" -gt 5 ]; then
        echo "   ⚠️  $pending pending learnings (review needed)"
    else
        echo "   ✓ $pending pending learnings"
    fi
fi

# Step 5: Check for stale logs
echo ""
echo "🗄️  Checking for stale logs..."
stale=$(find "$WORKSPACE/memory" -maxdepth 1 -name "*.md" -type f -mtime +90 2>/dev/null | wc -l | tr -d ' ')
if [ "$stale" -gt 0 ]; then
    echo "   ⚠️  $stale logs need archiving (> 90 days old)"
else
    echo "   ✓ No stale logs"
fi

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Daily ops complete"
echo "  Today's log: memory/$TODAY.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
